services:
  postgres:
    container_name: cleanarchcruds-postgres
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cleanarchcruds
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: cleanarchcruds-pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cleanarchcruds.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  postgres_data: